### ISSUE TITLE
heartbeat timers are still on after connection is closed

### ISSUE THREAD

**Issue by vi-sh** [Polyconseil/aioamqp#111]
WARNING:aioamqp.protocol:Connection lost exc=BrokenPipeError(32, 'Broken pipe')
ERROR:asyncio:Exception in callback AmqpProtocol._heartbeat_timer_recv_timeout()
handle: <TimerHandle when=75311.867231919 AmqpProtocol._heartbeat_timer_recv_timeout()>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.5/site-packages/aioamqp/protocol.py", line 318, in _heartbeat_timer_recv_timeout
    self._stream_writer.close()
AttributeError: 'NoneType' object has no attribute 'close'

Steps to reproduce:
- Restart RabbitMQ server.

**Comment by RemiCardona** [comment]
Jackpot! You hit both #107 and #108 at the same time. Will look into both Real Soon™.

Cheers
