### ISSUE TITLE
Dropping python 3.3 & 3.4 support

### ISSUE THREAD

**Issue by dzen** [Polyconseil/aioamqp#123]
Hi,

I'm currently thinking of removing python 3.3 support.
What if aioamqp 0.9 drops it ?

**Comment by nhumrich** [comment]
DO IT!

**Comment by armata** [comment]
I'm fine with it :)

**Comment by dzen** [comment]
Well, as soon as we drop debian jessie in our dockers, I think we will drop 3.4 instead. Maintaining 3.3 and 3.4 is harder, since we can't use async, await, async for, and such.

still 1 or 2 month more :(

**Comment by hugovk** [comment]
CPython 3.3 reaches end of life this month.
https://en.wikipedia.org/wiki/CPython#Version_history

**Comment by hugovk** [comment]
Here's the pip installs for aioamqp from PyPI for the last month:
```
$ pypinfo --percent --pip aioamqp pyversion
python_version percent download_count
-------------- ------- --------------
3.6              64.8%          2,785
3.5              33.9%          1,456
3.4               0.8%             36
2.7               0.5%             22

```

**Comment by skewty** [comment]
I am in support of dropping both Python 3.3 and 3.4 support.  This, of course, allows the new `async`, `await` syntax.  Also, it would be nice if [PEP 484](https://www.python.org/dev/peps/pep-0484/) type hinting was provided while someone is going through the code.  It would be a great 2 for 1 deal! :)

**Comment by dzen** [comment]
hello,

We currently have a High dependency on python 3.4 for now.
As soon as we drop it, we will remove it from aioamqp :)

**Comment by dzen** [comment]
Done!
