### ISSUE TITLE
Timeout parameter seems to be not used in channels' module api

### ISSUE THREAD

**Issue by a-urth** [Polyconseil/aioamqp#128]
Which leads to impossibility to set timeout for `open`/`close` operations and all other operations using `_write_frame` method.
Is this intended behavior or just a bug?
Because I see no other possibility to set timeout for close operation (in case of lost connection in my particular case) and even async_timeout does not help.

**Comment by RemiCardona** [comment]
I guess it should have been stripped out as part of commit 8d86e29f649b930c5fef1f702adf65139fe91fe4 where the `no_wait` parameter was removed.

Thanks for pointing it out, any PR for this tiny cleanup will be appreciated.

Cheers
