### ISSUE TITLE
Tests sometimes fail when running locally

### ISSUE THREAD

**Issue by ilya-khaustov** [Polyconseil/aioamqp#138]
It makes sense to change default `AMQP_REFRESH_TIME` [taken from os.environ](https://github.com/Polyconseil/aioamqp/blob/master/aioamqp/tests/testcase.py#L185) from 3 to 5 as defined in `.travis.yml`.

**Comment by RemiCardona** [comment]
Yes, it's due to a not-so-minor change in rabbit 3.6.7

https://github.com/rabbitmq/rabbitmq-server/releases/tag/rabbitmq_v3_6_7

> #### Test Suites that use HTTP API
>
>Integration test suites that rely on HTTP API for listing
>or closing connections, channels, etc need to be adjusted with this plugin:
>
>    * We recommend reducing stats retention periods (see Hop, rabbit-hole)
>    * Because stats emission is now two-step and asynchronous, test suites may need
>    to wait for events to propagate before asserting on them (see Hop, rabbit-hole).

I've locally configured my rabbit server to have a much quicker stats propagation time, but it should just work out of the box.

Thanks for the reminder
