### ISSUE TITLE
The correct way of handling connection problems

### ISSUE THREAD

**Issue by greatvovan** [Polyconseil/aioamqp#144]
What is the correct approach of keeping application running in case of Rabbit connection problems?
I am imitating connection issues by disconnecting network cable (or enabling/disabling network adapter in Windows).

I tried:

- handling AMQP exceptions from protocol functions with subsequent reconnect,
- setting `heartbeat=30`,
- `on_error` callback,
- approach from https://github.com/Polyconseil/aioamqp/issues/65#issuecomment-301737344

Neither of this makes library reconnect in my test case. I am getting the following results:
- nothing throws any exceptions and `on_error` callback does not fire,
- in rare cases library functions throw exceptions and `on_error` fires, but any further call to protocol function (including `connect()`) hangs forever,
and eventually:
- message callback basically stops being called.

In the first case it is even impossible to identify that a problem exists, as everything looks like just there is no messages.
Does anybody have any idea?

My environment:
- CPython 3.6 (natively on Windows 8.1 or in Docker Toolbox),
- aioamqp 0.10.0.

**Comment by clodo** [comment]
Hi @greatvovan,
I have the same problem and I am trying [this](http://pika.readthedocs.io/en/0.10.0/examples/asynchronous_publisher_example.html) approach from pika library using futures and add_done_callback.
If it works, I'll let you know.

**Comment by RemiCardona** [comment]
Honestly, without reading your code, it's impossible to say where the issue is. The code in #65 is what I have had in production for months now and it's pretty robust.

Like I said in #65, the `on_error` callback is busted, don't use it.

If you can't provide a sample code that breaks, there's nothing I can do to help you out. Sorry.
