### ISSUE TITLE
how can i get queue length ?

### ISSUE THREAD

**Issue by inzem77** [Polyconseil/aioamqp#148]
Hello!
I read all examples and documentation but didn't find as i can get queue length

**Comment by inzem77** [comment]
for example asyncio queue has method empty()

**Comment by dzen** [comment]
Did you check AMQP's protocol documentation ?

**Comment by inzem77** [comment]
litle bit

**Comment by inzem77** [comment]
for example in pika
res = channel.queue_declare(
        callback=on_callback,
        queue="test",
        durable=True,
        exclusive=False,
        auto_delete=False,
        passive=True
    )
print 'Messages in queue %d' % res.method.message_count

**Comment by dzen** [comment]
Hello @inzem77.

If you did check the return of `queue_declare`, it should return a dict :
https://github.com/Polyconseil/aioamqp/blob/master/aioamqp/channel.py#L357

**Comment by inzem77** [comment]
ok, Thank you
