### ISSUE TITLE
x-priority argument cannot have negative values on basic_consume

### ISSUE THREAD

**Issue by lphuberdeau** [Polyconseil/aioamqp#153]
The RabbitMQ documentation explicitly states that the x-priority argument can have positive or negative values. However, when a negative value is provided, it is packed as an unsigned integer, causing a `struct.error: argument out of range` error.

```
    def write_long(self, integer):
        self.payload.write(struct.pack('!I', integer))
```

**Comment by RemiCardona** [comment]
So indeed, Rabbit's documentation says:

> Set the `x-priority` argument in the `basic.consume` method to an integer value. Consumers which do not specify a value have priority 0. Larger numbers indicate higher priority, and both positive and negative numbers can be used.

https://www.rabbitmq.com/consumer-priority.html

Which does mention negative integers.

*But*, there's no mention of signed integers in the AMQP spec. As per section "4.2.5.1 Integers" of https://www.rabbitmq.com/resources/specs/amqp0-9-1.pdf (emphasis mine):

> AMQP defines these native integer types:
> * Unsigned octet (8 bits).
> * Unsigned short integers (16 bits).
> * Unsigned long integers (32 bits).
> * Unsigned long long integers (64 bits).
>
> Integers and string lengths are **always unsigned** and held in network byte order.

So, I'm not quite sure what to do here…

Cheers

**Comment by lphuberdeau** [comment]
Nice contradiction here.

I've searched for what is being done in the Java client library. It seems like they try really hard not to look at this problem.

https://github.com/rabbitmq/rabbitmq-java-client/blob/077f66fd169e2dedbe5c3aebb598b825ee8da8ac/src/main/java/com/rabbitmq/client/impl/ValueWriter.java#L97

```
    /** Public API - encodes an integer. */
    public final void writeLong(int l)
        throws IOException
    {
        // java's arithmetic on this type is signed, however it's
        // reasonable to use ints to represent the unsigned long
        // type - for values < Integer.MAX_VALUE everything works
        // as expected
        out.writeInt(l);
    }
```

There is an obvious workaround, which is not to use negative numbers.

**Comment by dzen** [comment]
Hi.

I just found a post about priority with rabbitmq : https://www.rabbitmq.com/priority.html

It states that a priority is between 0 and 255 : 

```The message priority field is defined as an unsigned byte, so in practice priorities should be between 0 and 255.```

It also says that priority is "vague" in AMQP specs.

Did you find other implementations (maybe using python ?) using signed values?

**Comment by lphuberdeau** [comment]
Message priority is not the same thing as consumer priority. X-Priority is
not limited to 255.

**Comment by dave-shawley** [comment]
FWIW, the "AMQP-defined Domains" section of the [generated AMQP 0-9-1 spec](https://www.rabbitmq.com/resources/specs/amqp-xml-doc0-9-1.pdf) includes signed and unsigned integers.  Section 4.2.5.1 does indicate that _field table values_ are limited to unsigned integers though you have to include the context of section 4.2.5 to see this (emphasis mine as well):

> 4.2.5 AMQP Data Fields
> AMQP has two levels of data field specification: the native data fields used for method arguments, and the data fields passed between applications in field tables. **Fields tables hold a superset of the native data fields.**
>
> 4.2.5.1 Integers
> AMQP defines these native integer types:
> - Unsigned octet (8 bits).
> - Unsigned short integers (16 bits).
> - Unsigned long integers (32 bits).
> - Unsigned long long integers (64 bits).
> Integers and string lengths are always unsigned and held in network byte order. We make no attempt to optimise the case when two low-high systems (e.g. two Intel CPUs) talk to each other.

I believe that the unsigned limitation is restricted to field table values only.  That being said, the formal grammar (section 4.2.1) explicitly allows for both signed and unsigned integers in `field-array`. A colleague of mine ran into this a month or so ago in pamqp (see https://github.com/gmr/pamqp/commit/78e82304a0592ae677af882ae50d6d34630f648b).  He ended up with an interesting implementation of encoding integers into tables (see [table_integer](https://github.com/gmr/pamqp/blob/88689db589d737ce037a2ef5ab67c42dd7019536/pamqp/encode.py#L309)) that chooses the encoded type based on value.  This works with the brokers that we know of.

I dug around the source for the Java and C++ qpid brokers and both support signed and unsigned integers values in tables.  [qpid-broker-j](https://github.com/apache/qpid-broker-j/blob/master/broker-core/src/main/java/org/apache/qpid/server/protocol/v0_8/AMQType.java) seems to only support unsigned bytes and unsigned shorts.  [qpid-cpp](https://github.com/apache/qpid-cpp/blob/91ed1489de7ab74d99f9d7198b90583454e96c5e/src/qpid/amqp/Encoder.cpp) supports 8, 16, 32, and 64 bit signed and unsigned types.  The Java implementation will never write an unsigned table field AFAICT but the C++ implementation certainly will.

I agree that the docs on consumer priorities is vague but I believe that the intent is to accept any "integer" value.  Indeed, the implementation of priority queues [accepts any integer type](https://github.com/rabbitmq/rabbitmq-server/blob/3ae27d2e5a0128c65d1e1312a23ef72103298e9a/src/rabbit_priority_queue.erl#L128-L139).  Is the approach for encoding table values from [pamqp](https://github.com/gmr/pamqp/blob/88689db589d737ce037a2ef5ab67c42dd7019536/pamqp/encode.py#L309) acceptable?

**Comment by dzen** [comment]
@dave-shawley There is a PR to use pamqp to encode / decode AMQP's frame.

**Comment by dzen** [comment]
@dave-shawley would you please test with master, since we now use pamqp to encode / decode frames ?
