### ISSUE TITLE
Support for an async logging

### ISSUE THREAD

**Issue by diogommartins** [Polyconseil/aioamqp#171]
Currently protocol.py and channel.py have their own logger. I use an async logging implementation[1] and it would be nice to have the possibility of nonblocking log calls at aioamqp. What do you guys think about that ? Also, would you be confortable with changing the interfaces of `AmqpProtocol` an `Channel` so that it would be possible to pass a logger and remove the global `logger` ? 

[1] [https://github.com/B2W-BIT/aiologger](https://github.com/B2W-BIT/aiologger)

**Comment by dzen** [comment]
Hello @diogommartins ;

I'm not comfortable with changing all logging calls to a coroutine call : it means breaking the official logger interface.
A proper way to interface an asyncio logger should be like this one : https://github.com/aio-libs/aiologstash : they create a new handler responsible for the network stack using asyncio, which abstract the asyncio complexity in the code.

**Comment by diogommartins** [comment]
Thanks a lot for the feedback, i'm gonna check it out 😁
