### ISSUE TITLE
Support for accessing message headers?

### ISSUE THREAD

**Issue by tbradshaw** [Polyconseil/aioamqp#18]
Thanks for writing and open sourcing this library.  It's great to be able to work with AMQP and asyncio already.

I was curious if there were any current plans for supporting access to message headers.  I have a messaging pattern that requires the consumer to interrogate the message headers before working with the body, and those attributes are currently unavailable with the current implementation.

Some libraries provide a "message" class that has accessing the content and headers of a message (txamqp is the library I have the most experience with), which might be an option.

Thanks again.

**Comment by dzen** [comment]
Hello,

since @mwfrojdman work on aioamqp, you can now access the body, the enveloppe and properties in the callback.
