### ISSUE TITLE
rabbitmqctl list_queues via aioamqp

### ISSUE THREAD

**Issue by vgoklani** [Polyconseil/aioamqp#192]
Hello - how would i replicate the results of "rabbitmqctl list_queues" via aioamqp?

Thanks!

**Comment by dzen** [comment]
Hi @vgoklani,

There is no way in the AMQP Protocol to list the queues.
You may want to acces to those info via the rabbitmq management HTTP Json API:

https://www.rabbitmq.com/management.html
