### ISSUE TITLE
Init login method default value 'AMQPLAIN'

### ISSUE THREAD

**Issue by MelvinLikeABird** [Polyconseil/aioamqp#214]
In the __init__.py file 
The default value of login_method is 'AMQPLAIN'.

In protocol.py there is a warning : 
`logger.warning('only PLAIN login_method is supported, falling back to AMQPLAIN')`

The new default value of login_method should be 'PLAIN'

**Comment by dzen** [comment]
https://github.com/Polyconseil/aioamqp/pull/215

**Comment by dzen** [comment]
Closed with https://github.com/Polyconseil/aioamqp/commit/f004c52275e62461c31afc3fce5e63d82e4c07e9
