### ISSUE TITLE
Testing with pamqp 3.0

### ISSUE THREAD

**Issue by gmr** [Polyconseil/aioamqp#216]
I plan on releasing pamqp 3.0 soon and wanted to make sure you all were aware of the changes that are making it into 3.0 and give you an opportunity to report any issues prior to its release.

Please see the version history @ https://pamqp.readthedocs.io/en/latest/history.html

**Comment by dzen** [comment]
Thanks for the notification @gmr !

We should probably start by creating a PR thats will tests aioamqp with the latest pamqp version ?

**Comment by gmr** [comment]
Makes sense, but be aware there are structural changes to the library and I would not expect it to work as a drop-in replacement.

**Comment by dzen** [comment]
@gmr seems we have a regression on `frame_parts` which is now a private method.
https://github.com/gmr/pamqp/pull/15

Any chance to convert it to a public method again ?

**Comment by gmr** [comment]
Sure, forgot about that.

**Comment by dzen** [comment]
Another issue : There are now default value in a few __init__ function that where optionnal.
For instance, the delivery_mode is now 0 but this is an incorrect value
https://github.com/gmr/pamqp/blob/a35d0294ab5bc7ab335ff914d90bb19f05bd00e9/pamqp/commands.py#L2285 V.S. 
https://github.com/gmr/pamqp/blob/master/pamqp/commands.py#L2339

**Comment by RemiCardona** [comment]
Work done in https://github.com/Polyconseil/aioamqp/pull/219 and pamqp 3.1.0 support added in 95cb1600d7caa1c823a0cd63255927e67ab02d69. @gmr thanks again for the heads up and the support
