### ISSUE TITLE
Is there any usage example or tutorial documents

### ISSUE THREAD

**Issue by tony-is-coding** [Polyconseil/aioamqp#220]
kindly: 
         acctually , it is hard to get how to use this library for me,  please give me something haveful!

**Comment by RemiCardona** [comment]
Have a look at the documentation, there are plenty of examples.

https://aioamqp.readthedocs.io/en/latest/examples/index.html

If you have specific issues with these examples or the rest of the documentation, feel free to open issues. Thanks
