### ISSUE TITLE
Republish the pypi docs to pick up Python3.9

### ISSUE THREAD

**Issue by erikseulean** [Polyconseil/aioamqp#225]
The pypi page seems out of date given that Python3.9 doesn't show up in the supported versions, while the code on github has support for 3.9 after this PR landed:
https://github.com/Polyconseil/aioamqp/commit/388d38f28c6d5b7e6a50135de6b8ea9c44ccd6a6

**Comment by michael-k** [comment]
The linked commit (Oct 2020) is not part of the latest release (Nov 2019). See https://pypi.org/project/aioamqp/#history

GitHub lists tags/releases on a commits page, see https://github.com/Polyconseil/aioamqp/commit/54ade18e43d7da1e2613a3d05a51fb3d86311f41 for comparison:
![image](https://user-images.githubusercontent.com/152008/106591226-f0152b00-6545-11eb-87e5-8fb3433ba508.png)

**Comment by erikseulean** [comment]
Oh okay, sorry about this. Any plans for a new release that would include the 3.9 version ?

**Comment by RemiCardona** [comment]
beta release now available: https://pypi.org/project/aioamqp/0.15.0b1/

Please let me know if you have any issues (or if it works for you!), final release will hopefully be done in a couple weeks at most.
