### ISSUE TITLE
Ready for release on pypi?

### ISSUE THREAD

**Issue by scailer** [Polyconseil/aioamqp#231]
We are looking forward to py3.10 support. I have tested my code with the current aioamqp and believe it is ready for use.
Do you have any plans to release on pypi? Or pre-release (0.15b1), which will not be the new default version.

**Comment by RemiCardona** [comment]
Just released 0.15.0b1 on pypi: https://pypi.org/project/aioamqp/0.15.0b1/

Thanks for your patience, let me know how it works for you.

Cheers
