### ISSUE TITLE
Ack'ing messages inside the consumer's callback

### ISSUE THREAD

**Issue by kflavin** [Polyconseil/aioamqp#39]
I was able to get  a working consumer going using your examples, but I'm trying to figure out how to acknowledge messages from within a callback passed to basic_consume().  I have something that looks like this:

```python
yield from channel.basic_consume(queue_name, callback=callback)
```

And then my co-routine looks roughly like this:

```python
@asyncio.coroutine
def callback(body, envelope, properties):
    loop = asyncio.get_event_loop()
    loop.create_task(do_work(body))
```

It doesn't look like I can acknowledge the message from within the callback.  When using other synchronous AMQP clients, such as pika, the channel is passed to the callback, and then I can do something like ch.basic_ack().  Is there another approach?  Or some other reason why this isn't viable with an asynchronous model?  I'm fairly new to asyncio.

Thanks very much for your work on this project, I've found it to be helpful.

**Comment by dzen** [comment]
Hello Kyle,

For the moment, when you consume data from a channel which is 'consume
enabled' the library waits for the coroutine to finish the job before doing
something else. It means that if you're having a huge amount of data from
this channel, each callback call will wait for it to *finish* before
sending anything else to the server on this *channel*.

That's why we are using more than one channel, for instance channels that
are dealing with data from rabbitmq and channels that are only dealing with
"commands" actions.

Le vendredi 10 juillet 2015, Kyle Flavin <notifications@github.com> a
écrit :

> I was able to get a working consumer going using your examples, but I'm
> trying to figure out how to acknowledge messages from within a callback
> passed to basic_consume(). I have something that looks like this:
>
> yield from channel.basic_consume(queue_name, callback=callback)
>
> And then my co-routine looks roughly like this:
>
> @asyncio.coroutinedef callback(body, envelope, properties):
>     loop = asyncio.get_event_loop()
>     loop.create_task(do_work(body))
>
> It doesn't look like I can acknowledge the message from within the
> callback. When using other synchronous AMQP clients, such as pika, the
> channel is passed to the callback, and then I can do something like
> ch.basic_ack(). Is there another approach? Or some other reason why this
> isn't viable with an asynchronous model? I'm fairly new to asyncio.
>
> Thanks very much for your work on this project, I've found it to be
> helpful.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Polyconseil/aioamqp/issues/39>.
>


-- 
*Benoît CALVEZ*
*Polyconseil* | 26 rue de Berri | 75008 Paris

**Comment by kflavin** [comment]
> For the moment, when you consume data from a channel which is 'consume
enabled' the library waits for the coroutine to finish the job before doing
something else. It means that if you're having a huge amount of data from
this channel, each callback call will wait for it to *finish* before
sending anything else to the server on this *channel*.

That makes sense with what I was seeing.  I'm trying to make a REST call in the callback, which takes a couple seconds to complete, and I noticed it blocked, so I moved the call into do_work(), and then created a new task on the loop.  Code here (using asyncio.sleep() to simulate the REST call): https://gist.github.com/kflavin/69002e58d579e90f1f41

However, I'm still not sure how to go about acknowledging the messages.  Do I need to create a separate channel and acknowledge the messages there?  The consumer is processing messages, but they aren't being acked, so the message count just continues to grow on the server:

```
# rabbitmqctl list_queues
Listing queues ...
test-async-queue        121
```

**Comment by dzen** [comment]
Hi Kyle,

Le samedi 11 juillet 2015, Kyle Flavin <notifications@github.com> a écrit :

> For the moment, when you consume data from a channel which is 'consume
> enabled' the library waits for the coroutine to finish the job before doing
> something else. It means that if you're having a huge amount of data from
> this channel, each callback call will wait for it to *finish* before
> sending anything else to the server on this *channel*.
>
> That makes sense with what I was seeing. I'm trying to make a REST call in
> the callback, which takes a couple seconds to complete, and I noticed it
> blocked, so I moved the call into do_work(), and then created a new task on
> the loop. Code here (using asyncio.sleep() to simulate the REST call):
> https://gist.github.com/kflavin/69002e58d579e90f1f41
>
> However, I'm still not sure how to go about acknowledging the messages. Do
> I need to create a separate channel and
>
>
Yes exactly, it's what we usually do, because our consuming channel is
really overloaded by the messages.



> acknowledge the messages there? The consumer is processing messages, but
> they aren't being acked, so the message count just continues to grow on the
> server:
>
> # rabbitmqctl list_queues
> Listing queues ...
> test-async-queue        121
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Polyconseil/aioamqp/issues/39#issuecomment-120547528>.
>


-- 
*Benoît CALVEZ*
*Polyconseil* | 26 rue de Berri | 75008 Paris

**Comment by kflavin** [comment]
Got it, thanks!  I'll give that a try.
