### ISSUE TITLE
Port to python 3.5

### ISSUE THREAD

**Issue by mpaolini** [Polyconseil/aioamqp#50]

**Comment by smurfix** [comment]
It's probably too early to replace all @asyncio/coroutine/yield from pairs with async/await, py3.4 is still too wide-spread and the two schemes are mostly compatible.

However, using Python 3.5 does break some tests.

**Comment by dzen** [comment]
More over, I don't see python 3.5 coming on debian ( the most interesting link must be https://lists.debian.org/debian-python/2015/06/msg00036.html)

Keeping the compatibility from 3.4 to 3.5 looks like pain :(

**Comment by smurfix** [comment]
Python 3.5 is on Debian experimental and is able to run 3.4 code just fine.
The only problem is that it exposes a nasty concurrency bug in httplib2 (used by pyrabbit) which I just submtted a pull request for.

**Comment by smurfix** [comment]
All tests now pass when using 3.5, at least on my machine.

AFAICT there are no plans to remove yield-from style coroutines from Python3.
Thus IMHO this issue can be closed.

**Comment by mpaolini** [comment]
then we just need to add python 3.5 to the tox config

**Comment by mpaolini** [comment]
travis config I mean

**Comment by smurfix** [comment]
On 20.11.2015 09:36, Marco Paolini wrote:
>
> then we just need to add python 3.5 to the tox config
>
Travis config updated. Thanks for noticing.

-- 
-- Matthias Urlichs

**Comment by dzen** [comment]
Imho the first fix should be a port of asyncio.async() to asyncio.ensure_future() ?

**Comment by dzen** [comment]
It seems pyrabbit is not python 3.5 compatible :(

**Comment by smurfix** [comment]
@dzen pyrabbit itself is perfectly 3.5 compatible. httplib2 is not.
My pull request to fix this (cf. my comment from Nov 19th, above) is here: https://github.com/jcgregorio/httplib2/pull/320

**Comment by dzen** [comment]
yes, for sure, I didn't go deeper this weekend to know why pyrabbit fails on thoses CONNRESET :)

thank you for the patch on httplib2

**Comment by dzen** [comment]
Hello all,

We migrated to the git version of pyrabbit. Tests are passing.

**Comment by MaxOvcharov** [comment]
Hello all,
At this moment, does aioamqp ported to python 3.5 syntax?

**Comment by RemiCardona** [comment]
No, we're still compatible with 3.4.

**Comment by MaxOvcharov** [comment]
Ok, thank you. Do you planning to do this?

**Comment by dzen** [comment]
Hi @MaxOvcharov.

We still have a lots of python 3.4 running in our production.
As soon as we migrate them all, we will work on using the new syntax.
