### ISSUE TITLE
Track flacky tests

### ISSUE THREAD

**Issue by dzen** [Polyconseil/aioamqp#51]
If I look at the travis build history, I think there are some flacky tests, or some Tasks are not cleanly terminated.

https://travis-ci.org/Polyconseil/aioamqp/builds

**Comment by dzen** [comment]
@smurfix  fixed two tests which didn't closed their connections to the rabbit.

Since then, the build is more stable

**Comment by RemiCardona** [comment]
Since commit a0b23e410e2fca9c3cea60d6a4ffd91eca5b4f2d, test cases now create their own vhost with a random name, effectively sandboxing tests. There's now virtually no way for any 2 tests to step on each other's toes.
