### ISSUE TITLE
RPC call documentation/examples

### ISSUE THREAD

**Issue by zloidemon** [Polyconseil/aioamqp#53]
Would you like add  documentation/examples to creation of rpc server/client?

**Comment by dzen** [comment]
I'm waiting a refactor branch to be merged. Then I'll work on aioamqp documentation.

**Comment by dzen** [comment]
Hello @zloidemon,

I've updated the documentation and the examples:
http://aioamqp.readthedocs.org/en/latest/examples/rpc.html
https://github.com/Polyconseil/aioamqp/blob/master/examples/rpc_client.py
https://github.com/Polyconseil/aioamqp/blob/master/examples/rpc_server.py
