### ISSUE TITLE
Please don't check the basic_consume callback for iscoroutinefunction

### ISSUE THREAD

**Issue by smurfix** [Polyconseil/aioamqp#55]
```
aioamqp.exceptions.ConfigurationError: basic_consume requires a coroutine callback
```
This is a spurious error.
One might want to use tools like ``functools.partial``, or a nested function, to create the callback. Example:
```
yield from my_channel.basic_consume(my_queue, callback=functools.partial(self._on_rpc, my_data))
```
Checking for None (or maybe ``callable()``) should be sufficient.

**Comment by dzen** [comment]
This problem is hard to solve, since a coroutine is also a callable :(

**Comment by smurfix** [comment]
With Python 3.4 it's possible to set ```function._is_coroutine=True``` to circumvent the test, but that's undocumented and not particularly future-proof …

**Comment by dzen** [comment]
Okay. the developper will have a nice error if he does not provide a coroutine :P

**Comment by dzen** [comment]
@smurfix any though ? Sorry for the API compatibility but removing the check without modifying the method signature didn't have any sense (to me).

**Comment by smurfix** [comment]
pika uses the same style (i.e. self, callback queue="", …) so this is OK with me.

It's not incompatible if the caller habitually uses keyword-only calling conventions. ;-)
