### ISSUE TITLE
TypeError: basic_consume() got multiple values for argument 'callback'

### ISSUE THREAD

**Issue by ariddell** [Polyconseil/aioamqp#62]
Upgrading from 0.4.0 to 0.5.1 with no code changes I get this error. Did the API change?

**Comment by ariddell** [comment]
Nevermind, I figured it out. Argument order changed or explicit keywords were added, I think.

**Comment by dzen** [comment]
Hello Allen,

We changed the basic_consume definition because the callback is now required. The method arguments makes sense now :)
