### ISSUE TITLE
Question: is it better than asynqp ?

### ISSUE THREAD

**Issue by socketpair** [Polyconseil/aioamqp#82]
https://github.com/benjamin-hodgson/asynqp

**Comment by dzen** [comment]
Hello @socketpair,

I've never tried asynqp, but this project looks great, with a sweet API.
Since you've opened the same issue on this project, to let the author tell if his project is better than aioamqp, you probably have to use the project you'll prefer :)

**Comment by mastak** [comment]
It seems there is no `exchange_bind` method in `asynqp`. 

And the source code of `aioamqp` is much more readeble, as for me =)

**Comment by ambivalentno** [comment]
Acknowledgement here is a coroutine, while in asynqp (imho) it's synchronous.

**Comment by mpaolini** [comment]
> Acknowledgement here is a coroutine, while in asynqp (imho) it's synchronous.
@ambivalentno not really meaningful as the `basic_client_ack` in aioamqp never yields (even if it is a coroutine). In `asyncio` usually writes are synchronous because they just write to a buffer that will be emptied by the event loop when possible.

**Comment by RemiCardona** [comment]
Not much for us to do here. If you have any specific issues with aioamqp, please file another issue and we'll try to work on it.

Cheers
