### ISSUE TITLE
pip installs version 0.6.0

### ISSUE THREAD

**Issue by avigmati** [Polyconseil/aioamqp#99]
today i installed aioamqp and version is 0.6.0

**Comment by RemiCardona** [comment]
You're right, `pip search aioamqp` returns 0.6.0 as the latest version. I have no idea why that happens. https://pypi.python.org/pypi/aioamqp does list 0.7.0 as the latest release.

Weirder still (in a python 3.5 `venv`):
```
$ pip install -U pip
[...]
Successfully installed pip-8.1.2
$ pip search aioamqp
aioamqp (0.6.0)  - AMQP implementation using asyncio
$ pip install aioamqp==0.7.0
Collecting aioamqp==0.7.0
  Downloading aioamqp-0.7.0-py33.py34-none-any.whl
Installing collected packages: aioamqp
Successfully installed aioamqp-0.7.0
```

Unfortunately, I don't have access to the pypi project so this will have to wait until @dzen looks at it. Until then, just force the latest version when writing the dependency.

Thanks for the report.

Cheers

**Comment by xavfernandez** [comment]
`pip search` uses an xmlrpc API of PyPI which is notoriously out-of-sync while `pip install/list/wheel` commands use the http simple "API" (i.e. this page: https://pypi.python.org/simple/aioamqp/ ) which is the reference and holds the *Truth*.

Things are likely to improve with the upcoming `warehouse` rewrite of PyPI.

**Comment by RemiCardona** [comment]
Actually, in a fresh `venv`:

```
$ pip install aioamqp
Collecting aioamqp
  Downloading aioamqp-0.7.0-py33.py34-none-any.whl
Installing collected packages: aioamqp
Successfully installed aioamqp-0.7.0
```

So as far as I'm concerned, there's no bug for us to fix. @avigmati: make sure you're using the latest pip version, that's about as much advice I can offer for now.

Cheers

**Comment by avigmati** [comment]
ok, thanks

2016-05-17 12:07 GMT+03:00 Rémi Cardona <notifications@github.com>:
